"""Generate paper/numbers.tex: every numeric claim in the manuscript comes from
results/ tables through this module (single source of truth; no hand copying).

Run:  python -m sgtc.fill_numbers
"""
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results" / "tables"
OUT = ROOT / "paper" / "numbers.tex"

macros = {}


def m(name, value, fmt="{:.3f}"):
    macros[name] = fmt.format(value) if isinstance(value, float) else str(value)


def cell(method, ratio, col, t1):
    r = t1[(t1.method == method) & (t1.ratio == ratio)]
    return float(r[col].iloc[0]) if len(r) else float("nan")


def run():
    # ---------- Table I ----------
    t1 = pd.read_csv(RES / "table1.csv")
    m("LccBase", cell("baseline", 1, "lcc", t1))
    m("SrccBase", cell("baseline", 1, "srcc", t1))
    m("RmseBase", cell("baseline", 1, "rmse", t1))
    for ratio in [2, 3, 4]:
        rn = {2: "Two", 3: "Three", 4: "Four"}[ratio]
        for meth, tag in [("merge", "Merge"), ("prune", "Prune"),
                          ("sgtc_w", "Sgtcw"), ("sgtc", "Sgtc"), ("tome", "Tome")]:
            m(f"Lcc{tag}{rn}", cell(meth, ratio, "lcc", t1))
            m(f"Srcc{tag}{rn}", cell(meth, ratio, "srcc", t1))
            m(f"Rmse{tag}{rn}", cell(meth, ratio, "rmse", t1))
        m(f"LccRand{rn}", cell("random_lcc", ratio, "lcc", t1))

    m("DLccMergeTwo", cell("merge", 2, "lcc", t1) - cell("baseline", 1, "lcc", t1), "{:+.3f}")
    m("DLccMergeThree", cell("merge", 3, "lcc", t1) - cell("baseline", 1, "lcc", t1), "{:+.3f}")
    m("DLccMergeFour", cell("merge", 4, "lcc", t1) - cell("baseline", 1, "lcc", t1), "{:+.3f}")
    rmse_gain = 1 - cell("merge", 4, "rmse", t1) / cell("baseline", 1, "rmse", t1)
    m("RmseGainPct", rmse_gain * 100, "{:.0f}")

    sig = t1[t1.method == "merge_vs_sgtc_t"]
    for ratio in [2, 3, 4]:
        rn = {2: "Two", 3: "Three", 4: "Four"}[ratio]
        r = sig[sig.ratio == ratio]
        if len(r):
            m(f"PMerge{rn}", float(r["p"].iloc[0]), "{:.1e}")

    # ---------- diagnosis ----------
    d = json.loads((RES / "shuffle_diagnosis.json").read_text())
    m("DLccChan", d["original"]["lcc_mean"] - d["chan_shuffle"]["lcc_mean"], "{:.3f}")
    m("LccChanShuf", d["chan_shuffle"]["lcc_mean"])
    m("LccBlock", d["block_shuffle"]["lcc_mean"])

    # ---------- ablation ----------
    t2 = pd.read_csv(RES / "table2.csv")
    tagmap = {"full": "Full", "random": "Rand", "cosine": "Cos", "global": "Glob",
              "tome": "TomeII", "sgtc_w": "SgtcwEq", "sgtc_w_cos": "SgtcwCos",
              "sgtc_w_rand": "SgtcwRand", "attention": "Att"}
    for _, r in t2.iterrows():
        tag = tagmap.get(r["variant"])
        if tag and not pd.isna(r.get("lcc")):
            m(f"AblLcc{tag}", float(r["lcc"]))

    # ---------- cross-domain ----------
    methods = [("baseline", "NisqaBase"), ("sgtc", "NisqaSgtc"),
               ("sgtc_w", "NisqaSgtcw"), ("tome", "NisqaTome"),
               ("prune2", "NisqaPrune"), ("merge2", "NisqaMerge")]
    if (RES / "table3.csv").exists():
        t3 = pd.read_csv(RES / "table3.csv")
        for meth, tag in methods:
            r = t3[t3.method == meth]
            if len(r):
                m(f"Lcc{tag}", float(r["lcc"].iloc[0]))
                m(f"Srcc{tag}", float(r["srcc"].iloc[0]))
                m(f"Rmse{tag}", float(r["rmse"].iloc[0]))
    for _, tag in methods:
        for pre in ["Lcc", "Srcc", "Rmse"]:
            macros.setdefault(f"{pre}{tag}", "??")

    # ---------- cross-backbone ----------
    cb = RES / "cross_backbone.json"
    if cb.exists():
        j = json.loads(cb.read_text())
        for bb, tag in [("hubert", "Hub"), ("wavlm", "Wlm")]:
            if bb in j:
                m(f"Lcc{tag}Base", j[bb]["baseline"]["lcc"])
                m(f"Lcc{tag}SgtcTwo", j[bb]["sgtc2"]["lcc"])
                m(f"Lcc{tag}SgtcFour", j[bb]["sgtc4"]["lcc"])
                if "merge2" in j[bb]:
                    m(f"Lcc{tag}Merge", j[bb]["merge2"]["lcc"])
                    m(f"Srcc{tag}Merge", j[bb]["merge2"]["srcc"])
                    m(f"Rmse{tag}Merge", j[bb]["merge2"]["rmse"])
    for tag in ["Hub", "Wlm"]:
        for suf in ["Base", "SgtcTwo", "SgtcFour", "Merge"]:
            macros.setdefault(f"Lcc{tag}{suf}", "??")
            if suf == "Merge":
                macros.setdefault(f"Srcc{tag}{suf}", "??")
                macros.setdefault(f"Rmse{tag}{suf}", "??")

    # ---------- deploy ----------
    dep = RES / "sgtc_deploy.json"
    if dep.exists():
        j = json.loads(dep.read_text())
        m("LccDeployTwo", j["accuracy"]["2x"]["lcc"])
        m("SpeedDeploy", j["speedup"], "{:.2f}")
    macros.setdefault("LccDeployTwo", "??")
    macros.setdefault("SpeedDeploy", "??")

    lines = ["% AUTO-GENERATED by sgtc.fill_numbers -- do not edit by hand"]
    for k in sorted(macros):
        v = macros[k]
        if v == "??":
            lines.append(f"\\newcommand{{\\{k}}}{{\\textbf{{??}}}}")
        else:
            lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(macros)} macros -> {OUT}")


if __name__ == "__main__":
    run()
